{{- $prefix := include "parasol-insurance-tenant.prefix" . -}}
{{- range $ns := list "build" "dev" "prod" }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ $prefix }}-{{ $ns }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
{{- end }}
