{{- $prefix := include "parasol-insurance-tenant.prefix" . -}}
{{- range $ns := list "build" "dev" "prod" }}
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: tenant-quota
  namespace: {{ $prefix }}-{{ $ns }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  hard:
    limits.cpu: {{ $.Values.resourceQuota.limits.cpu | quote }}
    limits.memory: {{ $.Values.resourceQuota.limits.memory | quote }}
    requests.cpu: {{ $.Values.resourceQuota.requests.cpu | quote }}
    requests.memory: {{ $.Values.resourceQuota.requests.memory | quote }}
    requests.storage: {{ $.Values.resourceQuota.requests.storage | quote }}
{{- end }}
