{{- if .Values.openshiftLightspeed.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
{{ include "app-of-apps.metadata" (dict "name" "openshift-mcp-server" "namespace" .Values.argocd.namespace "syncWave" "1") }}
spec:
  destination:
    namespace: openshift-mcp
    server: https://kubernetes.default.svc
  project: default
  source:
    path: automation/gitops/cluster/openshift-mcp-server
    repoURL: {{ .Values.gitops.repoURL }}
    targetRevision: {{ .Values.gitops.targetRevision }}
{{ include "app-of-apps.syncPolicy" . | indent 2 }}
{{- end }}
