apiVersion: argoproj.io/v1alpha1
kind: Application
{{ include "app-of-apps.metadata" (dict "name" "tenant-prereqs" "namespace" .Values.argocd.namespace "syncWave" "2") }}
spec:
  destination:
    namespace: {{ .Values.argocd.namespace }}
    server: https://kubernetes.default.svc
  project: default
  source:
    path: automation/gitops/cluster/tenant-prereqs
    repoURL: {{ .Values.gitops.repoURL }}
    targetRevision: {{ .Values.gitops.targetRevision }}
  {{ include "app-of-apps.syncPolicy" . | nindent 2 }}
